In [1]:
!pip install --pre deepchem

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 10.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.3/34.3 MB 21.8 MB/s eta 0:00:00


In [2]:
import deepchem as dc
dc.__version__

wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.
Instructions for updating:
experimental_relax_shapes is deprecated, use reduce_retracing instead
wandb: WARNING W&B installed but not logged in.  Run `wandb login` or set the WANDB_API_KEY env variable.


'2.8.1.dev'

In [3]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer = "GraphConv")

In [4]:
train_dataset, valid_dataset, test_dataset = datasets

In [5]:
print(train_dataset)

<DiskDataset X.shape: (902,), y.shape: (902, 1), w.shape: (902, 1), ids: ['CC(C)=CCCC(C)=CC(=O)' 'CCCC=C' 'CCCCCCCCCCCCCC' ...
 'Nc2cccc3nc1ccccc1cc23 ' 'C1CCCCCC1' 'OC1CCCCCC1'], task_names: ['measured log solubility in mols per litre']>


In [6]:
print(test_dataset)

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['c1cc2ccc3cccc4ccc(c1)c2c34' 'Cc1cc(=O)[nH]c(=S)[nH]1'
 'Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 ' ...
 'c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43' 'Cc1occc1C(=O)Nc2ccccc2'
 'OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O '], task_names: ['measured log solubility in mols per litre']>


In [11]:
test_dataset.y

array([[-1.60114461],
       [ 0.20848251],
       [-0.01602738],
       [-2.82191713],
       [-0.52891635],
       [ 1.10168349],
       [-0.88987406],
       [-0.52649706],
       [-0.76358725],
       [-0.64020358],
       [-0.38569452],
       [-0.62568785],
       [-0.39585553],
       [-2.05306753],
       [-0.29666474],
       [-0.73213651],
       [-1.27744393],
       [ 0.0081655 ],
       [ 0.97588054],
       [-0.10796031],
       [ 0.59847167],
       [-0.60149498],
       [-0.34988907],
       [ 0.34686576],
       [ 0.62750312],
       [ 0.14848418],
       [ 0.02268122],
       [-0.85310089],
       [-2.72079091],
       [ 0.42476682],
       [ 0.01300407],
       [-2.4851523 ],
       [-2.15516147],
       [ 1.00975056],
       [ 0.82588471],
       [-0.90390593],
       [-0.91067993],
       [-0.82455329],
       [ 1.26909819],
       [-1.14825397],
       [-2.1343556 ],
       [-1.15744727],
       [-0.1045733 ],
       [ 0.53073162],
       [-1.22567118],
       [-1

In [12]:
for x, y, w, id in test_dataset.itersamples():
  print(x, y, w, id)

<deepchem.feat.mol_graphs.ConvMol object at 0x7ff601b5bed0> [-1.60114461] [1.] c1cc2ccc3cccc4ccc(c1)c2c34
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012f8b10> [0.20848251] [1.] Cc1cc(=O)[nH]c(=S)[nH]1
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012f8590> [-0.01602738] [1.] Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012f8890> [-2.82191713] [1.] c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012fa750> [-0.52891635] [1.] C1=Cc2cccc3cccc1c23
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012f8ed0> [1.10168349] [1.] CC1CO1
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff6012fa610> [-0.88987406] [1.] CCN2c1ccccc1N(C)C(=S)c3cccnc23 
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff601029410> [-0.52649706] [1.] CC12CCC3C(CCc4cc(O)ccc34)C2CCC1=O
<deepchem.feat.mol_graphs.ConvMol object at 0x7ff60118a850> [-0.76358725] [1.] Cn2cc(c1ccccc1)c(=O)c(c2)c3cccc(c3)C(F)(F)F
<deepchem.feat.mol_graphs.C

In [26]:
for X, y, w, ids in test_dataset.iterbatches(batch_size = 32, epochs = 2, deterministic= True):
   print(y)

[[-1.60114461]
 [ 0.20848251]
 [-0.01602738]
 [-2.82191713]
 [-0.52891635]
 [ 1.10168349]
 [-0.88987406]
 [-0.52649706]
 [-0.76358725]
 [-0.64020358]
 [-0.38569452]
 [-0.62568785]
 [-0.39585553]
 [-2.05306753]
 [-0.29666474]
 [-0.73213651]
 [-1.27744393]
 [ 0.0081655 ]
 [ 0.97588054]
 [-0.10796031]
 [ 0.59847167]
 [-0.60149498]
 [-0.34988907]
 [ 0.34686576]
 [ 0.62750312]
 [ 0.14848418]
 [ 0.02268122]
 [-0.85310089]
 [-2.72079091]
 [ 0.42476682]
 [ 0.01300407]
 [-2.4851523 ]]
[[-2.15516147]
 [ 1.00975056]
 [ 0.82588471]
 [-0.90390593]
 [-0.91067993]
 [-0.82455329]
 [ 1.26909819]
 [-1.14825397]
 [-2.1343556 ]
 [-1.15744727]
 [-0.1045733 ]
 [ 0.53073162]
 [-1.22567118]
 [-1.66452995]
 [ 0.24525568]
 [-0.13215318]
 [-0.97067826]
 [-0.23376326]
 [ 1.21297072]
 [-1.2595412 ]
 [ 0.49686159]
 [ 0.22396595]
 [-0.44182199]
 [ 0.47895886]
 [ 0.08267956]
 [-1.51840498]
 [-0.34795364]
 [-0.83858516]
 [-0.13699176]
 [-2.59498796]
 [ 0.13106531]
 [ 0.09042128]]
[[ 1.18877785]
 [-0.82697258]
 [-1.168

In [31]:
test_dataset.to_dataframe()

X         y    w  \
0    <deepchem.feat.mol_graphs.ConvMol object at 0x... -1.601145  1.0   
1    <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.208483  1.0   
2    <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.016027  1.0   
3    <deepchem.feat.mol_graphs.ConvMol object at 0x... -2.821917  1.0   
4    <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.528916  1.0   
..                                                 ...       ...  ...   
108  <deepchem.feat.mol_graphs.ConvMol object at 0x... -1.656304  1.0   
109  <deepchem.feat.mol_graphs.ConvMol object at 0x...  0.743629  1.0   
110  <deepchem.feat.mol_graphs.ConvMol object at 0x... -2.420799  1.0   
111  <deepchem.feat.mol_graphs.ConvMol object at 0x... -0.209570  1.0   
112  <deepchem.feat.mol_graphs.ConvMol object at 0x...  1.014589  1.0   

                                                   ids  
0                           c1cc2ccc3cccc4ccc(c1)c2c34  
1                              Cc1cc(=O)[nH]c(=S)[nH]1  
2           Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4   
3                     c1ccc2c(c1)cc3ccc4cccc5ccc2c3c45  
4                                  C1=Cc2cccc3cccc1c23  
..                                                 ...  
108     ClC4=C(Cl)C5(Cl)C3C1CC(C2OC12)C3C4(Cl)C5(Cl)Cl  
109                                            c1ccsc1  
110                 c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43  
111                             Cc1occc1C(=O)Nc2ccccc2  
112  OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...  

[113 rows x 4 columns]

In [34]:
import numpy as np
X = np.random.random((10, 5))
y = np.random.random((10, 2))
dataset = dc.data.NumpyDataset(X, y)
print(dataset)
dataset.to_dataframe()

<NumpyDataset X.shape: (10, 5), y.shape: (10, 2), w.shape: (10, 1), ids: [0 1 2 3 4 5 6 7 8 9], task_names: [0 1]>


X1        X2        X3        X4        X5        y1        y2    w  \
0  0.364746  0.566801  0.832796  0.679384  0.276033  0.851017  0.104873  1.0   
1  0.244917  0.781149  0.256399  0.216631  0.520675  0.281768  0.222225  1.0   
2  0.744463  0.555727  0.905359  0.978987  0.026332  0.791950  0.627064  1.0   
3  0.929315  0.609594  0.448100  0.265147  0.981906  0.435590  0.706758  1.0   
4  0.025207  0.837610  0.998181  0.958193  0.893405  0.317585  0.204945  1.0   
5  0.566948  0.595478  0.086037  0.026614  0.069297  0.074212  0.440528  1.0   
6  0.814669  0.666510  0.134610  0.601447  0.914876  0.599561  0.505768  1.0   
7  0.661805  0.732994  0.971004  0.350417  0.972495  0.533107  0.986575  1.0   
8  0.496893  0.463581  0.735295  0.442064  0.755883  0.057277  0.496567  1.0   
9  0.374436  0.438084  0.274271  0.609492  0.308190  0.473803  0.535987  1.0   

  ids  
0   0  
1   1  
2   2  
3   3  
4   4  
5   5  
6   6  
7   7  
8   8  
9   9

In [36]:
import tempfile
with tempfile.TemporaryDirectory() as data_dir:
  disk_dataset = dc.data.DiskDataset.from_numpy(X=X, y=y, data_dir= data_dir)
  print(disk_dataset)


<DiskDataset X.shape: (10, 5), y.shape: (10, 2), w.shape: (10, 1), ids: [0 1 2 3 4 5 6 7 8 9], task_names: [0 1]>


In [40]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer = "GraphConv", splitter = "random")

In [41]:
[method for method in dir(dc.molnet) if "load_" in method]

['load_Platinum_Adsorption',
 'load_bace_classification',
 'load_bace_regression',
 'load_bandgap',
 'load_bbbc001',
 'load_bbbc002',
 'load_bbbc003',
 'load_bbbc004',
 'load_bbbc005',
 'load_bbbp',
 'load_cell_counting',
 'load_chembl',
 'load_chembl25',
 'load_clearance',
 'load_clintox',
 'load_delaney',
 'load_factors',
 'load_freesolv',
 'load_function',
 'load_hiv',
 'load_hopv',
 'load_hppb',
 'load_kaggle',
 'load_kinase',
 'load_lipo',
 'load_mp_formation_energy',
 'load_mp_metallicity',
 'load_muv',
 'load_nci',
 'load_pcba',
 'load_pdbbind',
 'load_perovskite',
 'load_ppb',
 'load_qm7',
 'load_qm8',
 'load_qm9',
 'load_sampl',
 'load_sider',
 'load_sweet',
 'load_thermosol',
 'load_tox21',
 'load_toxcast',
 'load_uspto',
 'load_uv',
 'load_zinc15']

In [42]:
len([method for method in dir(dc.molnet) if "load_" in method])

45

In [43]:
tasks

['measured log solubility in mols per litre']

In [44]:
datasets

(<DiskDataset X.shape: (902,), y.shape: (902, 1), w.shape: (902, 1), ids: ['O=N(=O)c1cc(Cl)c(Cl)cc1' 'O=C2NC(=O)C1(CCCC1)C(=O)N2' 'CC1CO1' ...
  'ClCC#N' 'CCN(CC)C(=S)SCC(Cl)=C'
  'COC(=O)c1ccccc1OC2OC(COC3OCC(O)C(O)C3O)C(O)C(O)C2O'], task_names: ['measured log solubility in mols per litre']>,
 <DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['CC(C)OC(=O)C' 'CC(C)N(C(C)C)C(=O)SCC(=CCl)Cl' 'Cc1ccccc1O' ...
  'Clc1cccc(I)c1' 'Cc1ccc(C)cc1' 'CCCCCCCBr'], task_names: ['measured log solubility in mols per litre']>,
 <DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['COP(=S)(OC)Oc1ccc(SC)c(C)c1' 'CC12CCC3C(CCC4=CC(=O)CCC34C)C2CCC1C(=O)CO'
  'COc1ccc(cc1)C(c2ccc(OC)cc2)C(Cl)(Cl)Cl' ...
  'CC12CC(=O)C3C(CCC4=CC(=O)CCC34C)C2CCC1(O)C(=O)CO' 'Nc1nc(=O)[nH]cc1F'
  'CC(C)OC(=O)Nc1cccc(Cl)c1'], task_names: ['measured log solubility in mols per litre']>)

In [45]:
train, test, valid = datasets

In [46]:
train

<DiskDataset X.shape: (902,), y.shape: (902, 1), w.shape: (902, 1), ids: ['O=N(=O)c1cc(Cl)c(Cl)cc1' 'O=C2NC(=O)C1(CCCC1)C(=O)N2' 'CC1CO1' ...
 'ClCC#N' 'CCN(CC)C(=S)SCC(Cl)=C'
 'COC(=O)c1ccccc1OC2OC(COC3OCC(O)C(O)C3O)C(O)C(O)C2O'], task_names: ['measured log solubility in mols per litre']>

In [47]:
test

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['CC(C)OC(=O)C' 'CC(C)N(C(C)C)C(=O)SCC(=CCl)Cl' 'Cc1ccccc1O' ...
 'Clc1cccc(I)c1' 'Cc1ccc(C)cc1' 'CCCCCCCBr'], task_names: ['measured log solubility in mols per litre']>

In [48]:
valid

<DiskDataset X.shape: (113,), y.shape: (113, 1), w.shape: (113, 1), ids: ['COP(=S)(OC)Oc1ccc(SC)c(C)c1' 'CC12CCC3C(CCC4=CC(=O)CCC34C)C2CCC1C(=O)CO'
 'COc1ccc(cc1)C(c2ccc(OC)cc2)C(Cl)(Cl)Cl' ...
 'CC12CC(=O)C3C(CCC4=CC(=O)CCC34C)C2CCC1(O)C(=O)CO' 'Nc1nc(=O)[nH]cc1F'
 'CC(C)OC(=O)Nc1cccc(Cl)c1'], task_names: ['measured log solubility in mols per litre']>

In [59]:
type(train.ids)

numpy.ndarray

In [60]:
train.X[0]

In [61]:
transformers

In [62]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer = "ECFP", splitter = "scaffold")

[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerator
[20:09:18] DEPRECATION WARNING: please use MorganGenerat

In [63]:
train, valid, test = datasets

In [64]:
train

<DiskDataset X.shape: (902, 1024), y.shape: (902, 1), w.shape: (902, 1), ids: ['CC(C)=CCCC(C)=CC(=O)' 'CCCC=C' 'CCCCCCCCCCCCCC' ...
 'Nc2cccc3nc1ccccc1cc23 ' 'C1CCCCCC1' 'OC1CCCCCC1'], task_names: ['measured log solubility in mols per litre']>

In [65]:
valid

<DiskDataset X.shape: (113, 1024), y.shape: (113, 1), w.shape: (113, 1), ids: ['Nc1ncnc2nc[nH]c12 ' 'Nc1nc(O)nc2nc[nH]c12 '
 'Fc1cccc(F)c1C(=O)NC(=O)Nc2cc(Cl)c(F)c(Cl)c2F ' ...
 'OC(Cn1cncn1)(Cn2cncn2)c3ccc(F)cc3F '
 'FC(F)(F)c1cccc(c1)N2CC(CCl)C(Cl)C2=O' 'CC1(C)CON(Cc2ccccc2Cl)C1=O'], task_names: ['measured log solubility in mols per litre']>

In [66]:
test

<DiskDataset X.shape: (113, 1024), y.shape: (113, 1), w.shape: (113, 1), ids: ['c1cc2ccc3cccc4ccc(c1)c2c34' 'Cc1cc(=O)[nH]c(=S)[nH]1'
 'Oc1ccc(cc1)C2(OC(=O)c3ccccc23)c4ccc(O)cc4 ' ...
 'c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43' 'Cc1occc1C(=O)Nc2ccccc2'
 'OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)C(O)C3O '], task_names: ['measured log solubility in mols per litre']>

In [67]:
train.X[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [69]:
tasks, datasets, transformers = dc.molnet.load_tox21(featurizer="ECFP")
train_dataset, valid_dataset, test_dataset = datasets
print(train_dataset)

<DiskDataset X.shape: (6258, 1024), y.shape: (6258, 12), w.shape: (6258, 12), task_names: ['NR-AR' 'NR-AR-LBD' 'NR-AhR' ... 'SR-HSE' 'SR-MMP' 'SR-p53']>


In [70]:
train_dataset.to_dataframe()

X1   X2   X3   X4   X5   X6   X7   X8   X9  X10  ...        w4  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   
2     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000   
4     0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
6253  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.000000   
6254  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   
6255  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  ...  1.045464   
6256  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  1.045464   
6257  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.045464   

            w5        w6        w7        w8        w9       w10       w11  \
0     1.145758  1.056077  1.025581  1.172887  1.035424  1.055832  1.174908   
1     1.145758  1.056077  1.025581  0.000000  1.035424  1.055832  1.174908   
2     1.145758  1.056077  1.025581  1.172887  1.035424  1.055832  0.000000   
3     0.000000  0.000000  0.000000  1.172887  0.000000  1.055832  0.000000   
4     1.145758  1.056077  1.025581  1.172887  1.035424  1.055832  1.174908   
...        ...       ...       ...       ...       ...       ...       ...   
6253  0.000000  0.000000  0.000000  1.172887  0.000000  1.055832  0.000000   
6254  1.145758  1.056077  1.025581  0.000000  1.035424  1.055832  6.717300   
6255  1.145758  1.056077  1.025581  1.172887  1.035424  1.055832  6.717300   
6256  1.145758  1.056077  1.025581  0.000000  1.035424  0.000000  1.174908   
6257  1.145758  1.056077  1.025581  1.172887  1.035424  0.000000  0.000000   

           w12                                                ids  
0     1.052945                          CC(O)(P(=O)(O)O)P(=O)(O)O  
1     1.052945               CC(C)(C)OOC(C)(C)CCC(C)(C)OOC(C)(C)C  
2     1.052945                      OC[C@H](O)[C@@H](O)[C@H](O)CO  
3     0.000000           CCCCCCCC(=O)[O-].CCCCCCCC(=O)[O-].[Zn+2]  
4     1.052945                                  CC(C)COC(=O)C(C)C  
...        ...                                                ...  
6253  0.000000     Cc1cc(CCCOc2c(C)cc(-c3noc(C(F)(F)F)n3)cc2C)on1  
6254  1.052945  O=C1OC(OC(=O)c2cccnc2Nc2cccc(C(F)(F)F)c2)c2ccc...  
6255  1.052945                    CC(=O)C1(C)CC2=C(CCCC2(C)C)CC1C  
6256  1.052945  CC(C)CCC[C@@H](C)[C@H]1CC(=O)C2=C3CC[C@H]4C[C@...  
6257  1.052945  N#C[C@@H]1CC(F)(F)CN1C(=O)CNC1CC2CCC(C1)N2c1nc...  

[6258 rows x 1049 columns]

In [76]:
type(train_dataset.ids)

numpy.ndarray

In [77]:
train_dataset.w

array([[1.0448833 , 1.03636706, 1.12518597, ..., 1.05583151, 1.17490775,
        1.05294456],
       [1.0448833 , 1.03636706, 1.12518597, ..., 1.05583151, 1.17490775,
        1.05294456],
       [1.0448833 , 1.03636706, 1.12518597, ..., 1.05583151, 0.        ,
        1.05294456],
       ...,
       [1.0448833 , 1.03636706, 1.12518597, ..., 1.05583151, 6.71729958,
        1.05294456],
       [1.0448833 , 1.03636706, 1.12518597, ..., 0.        , 1.17490775,
        1.05294456],
       [1.0448833 , 1.03636706, 1.12518597, ..., 0.        , 0.        ,
        1.05294456]])

In [78]:
model = dc.models.MultitaskClassifier(n_tasks = 12, n_features = 1024, layer_sizes=[1000])

In [80]:
print(model)

In [81]:
model.fit(train_dataset, nb_epoch = 10)

0.4802923838297526

In [82]:
metric = dc.metrics.Metric(dc.metrics.roc_auc_score)

In [83]:
model.evaluate(train_dataset, [metric], transformers)

{'roc_auc_score': 0.959376835164096}

In [84]:
model.evaluate(test_dataset, [metric], transformers)

{'roc_auc_score': 0.6851054050452295}

In [85]:
print("training set score:", model.evaluate(train_dataset, [metric], transformers))
print("test set score:", model.evaluate(test_dataset, [metric], transformers))

training set score: {'roc_auc_score': 0.959376835164096}
test set score: {'roc_auc_score': 0.6851054050452295}


In [86]:
import deepchem as dc
import tensorflow as tf

In [87]:
keras_model = tf.keras.Sequential([
  tf.keras.layers.Dense(1000, activation='relu'),
  tf.keras.layers.Dropout(rate=0.5),
  tf.keras.layers.Dense(1)
])

In [88]:
model = dc.models.KerasModel(keras_model, dc.models.losses.L2Loss())

In [93]:

tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='ECFP', splitter='random')


In [94]:
train_dataset, valid_dataset, test_dataset = datasets

In [114]:
model.fit(train_dataset, nb_epoch=10)

AttributeError: 'str' object has no attribute 'as_numpy_dtype'

In [112]:
%env TF_USE_LEGACY_KERAS=True

env: TF_USE_LEGACY_KERAS=True


In [115]:
import torch

In [118]:
pytorch_model = torch.nn.Sequential(
    torch.nn.Linear(1024, 1000),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(1000, 1)
)

In [119]:
model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())

In [120]:
model.fit(train_dataset, nb_epoch=10)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x10 and 1024x1000)

In [121]:


import torch

pytorch_model = torch.nn.Sequential(
    torch.nn.Linear(1024, 1000),
    torch.nn.ReLU(),
    torch.nn.Dropout(0.5),
    torch.nn.Linear(1000, 1)
)
model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())

model.fit(train_dataset, nb_epoch=50)
print('training set score:', model.evaluate(train_dataset, [metric]))
print('test set score:', model.evaluate(test_dataset, [metric]))



RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x10 and 1024x1000)

In [129]:
import torch
import torch.nn as nn

# Define a simple model with dropout
class SimpleModel(tf.keras.Model):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.dense = tf.keras.layers.Dense(64, activation='relu')
        self.dropout = tf.keras.layers.Dropout(0.5)  # Dropout layer with 50% dropout rate

    def call(self, inputs, training=False):  # Add `training` argument
        x = self.dense(inputs)
        x = self.dropout(x, training=training)  # Pass `training` to dropout
        return x

# Create and use the model
pytorch_model = SimpleModel()



In [132]:
model = dc.models.TorchModel(pytorch_model, dc.models.losses.L2Loss())

model.fit(train_dataset, nb_epoch=50)
print('training set score:', model.evaluate(train_dataset, [metric]))
print('test set score:', model.evaluate(test_dataset, [metric]))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (100x10 and 1024x64)

In [131]:
import torch
import torch.nn as nn

# Define a simple model with dropout
class SimpleModel(nn.Module): # Change to inherit from nn.Module
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.dense = nn.Linear(1024, 64) # Change to PyTorch layers
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(0.5)  # Dropout layer with 50% dropout rate

    def forward(self, inputs):  # Change method name to forward
        x = self.dense(inputs)
        x = self.relu(x) # Add relu activation
        x = self.dropout(x)  # Pass `training` to dropout
        return x

# Create and use the model
pytorch_model = SimpleModel()

In [133]:
dc.__version__

'2.8.1.dev'

In [134]:
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = datasets

In [162]:
n_tasks = len(np.unique(tasks))

n_tasks = 599
n_tasks

599

In [159]:
unique_classes = np.unique(train_dataset.y)
len(unique_classes)

599

In [160]:
num_features = train_dataset.X[0].get_atom_features().shape[1]
num_features

75

In [166]:
n_tasks = len(np.unique(train_dataset.y))  # Set n_tasks to the number of unique classes
model = dc.models.torch_models.GraphConvModel(
    n_tasks=n_tasks,
    mode='classification',
    number_input_features=(num_features,64))  #

In [167]:
model.fit(train_dataset, nb_epoch=50)

ValueError: y has more than n_class unique elements.

In [169]:
from deepchem.models.layers import GraphConv, GraphPool, GraphGather
import tensorflow as tf
import tensorflow.keras.layers as layers

In [170]:
batch_size = 100

In [179]:
class GraphConvModelTensorflow(tf.keras.Model):
  def __init__(self):
    super(GraphConvModelTensorflow, self).__init__()
    self.gc1 = GraphConv(128, activation_fn=tf.nn.tanh)
    self.batch_norm1 = layers.BatchNormalization()
    self.gp1 = GraphPool()

    self.gc2 = GraphConv(128, activation_fn=tf.nn.tanh)
    self.batch_norm2 = layers.BatchNormalization()
    self.gp2 = GraphPool()

    self.dense1 = layers.Dense(256, activation=tf.nn.tanh)
    self.batch_norm3 = layers.BatchNormalization()
    self.readout = GraphGather(batch_size=batch_size)

    self.dense2 = layers.Dense(n_tasks*2)
    self.logits = layers.Reshape((n_tasks, 2))
    self.softmax = layers.Softmax()

  def call(self, inputs):
    gc1_output = self.gc1(inputs)
    batch_norm1_output = self.batch_norm1(gc1_output)
    gp1_output = self.gp1([batch_norm1_output] + inputs[1:])

    gc2_output = self.gc2([gp1_output] + inputs[1:])
    batch_norm2_output = self.batch_norm1(gc2_output)
    gp2_output = self.gp2([batch_norm2_output] + inputs[1:])

    dense1_output = self.dense1(gp2_output)
    batch_norm3_output = self.batch_norm3(dense1_output)
    readout_output = self.readout([batch_norm3_output] + inputs[1:])

    logits_output = self.logits(self.dense2(readout_output))
    return self.softmax(logits_output)



In [180]:
model = dc.models.KerasModel(GraphConvModelTensorflow(), loss=dc.models.losses.CategoricalCrossEntropy())

In [181]:
test_dataset.X[0]

In [188]:
from deepchem.metrics import to_one_hot
from deepchem.feat.mol_graphs import ConvMol
import numpy as np

def data_generator(dataset, epochs=1):
  for ind, (X_b, y_b, w_b, ids_b) in enumerate(dataset.iterbatches(batch_size, epochs,
                                                                   deterministic=False, pad_batches=True)):
    multiConvMol = ConvMol.agglomerate_mols(X_b)
    inputs = [multiConvMol.get_atom_features(), multiConvMol.deg_slice, np.array(multiConvMol.membership)]
    for i in range(1, len(multiConvMol.get_deg_adjacency_lists())):
      inputs.append(multiConvMol.get_deg_adjacency_lists()[i])
    labels = [to_one_hot(y_b.flatten(), 2).reshape(-1, n_tasks, 2)]
    weights = [w_b]
    yield (inputs, labels, weights)

In [189]:
model.fit_generator(data_generator(train_dataset, epochs=50))

AttributeError: 'KerasModel' object has no attribute '_checkpoint'